kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-person-service
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-person-service.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: amt-arrangor
        - application: amt-tiltak
        - application: amt-deltaker-bff
        - application: amt-deltaker
        - application: amt-distribusjon
        - application: amt-tiltaksarrangor-bff
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
          cluster: dev-gcp
        - application: veilarbvedtaksstotte
          namespace: obo
          cluster: dev-gcp
        - application: veilarboppfolging
          namespace: poao
          cluster: dev-gcp
        - application: logging
          namespace: nais-system
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: digdir-krr-proxy.intern.dev.nav.no
        - host: norg2.dev-fss-pub.nais.io
        - host: nom-api.intern.dev.nav.no
        - host: veilarbarena.dev-fss-pub.nais.io
        - host: kodeverk-api.nav.no
  env:
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.intern.dev.nav.no
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-gcp.poao.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.poao
    - name: NORG_URL
      value: https://norg2.dev-fss-pub.nais.io
    - name: KODEVERK_URL
      value: https://kodeverk-api.nav.no
    - name: KODEVERK_SCOPE
      value: api://dev-gcp.team-rocket.kodeverk-api/.default
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: NOM_SCOPE
      value: api://dev-gcp.nom.nom-api/.default
    - name: NOM_URL
      value: https://nom-api.intern.dev.nav.no
    - name: NOM_MOCK
      value: "true"
    - name: VEILARBARENA_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.dev-fss-pub.nais.io
    - name: ENDRING_PAA_BRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: SISTE_TILORDNET_VEILEDER_TOPIC
      value: pto.siste-tilordnet-veileder-v1
    - name: AKTOR_V2_TOPIC
      value: pdl.aktor-v2
    - name: SKJERMEDE_PERSONER_STATUS_TOPIC
      value: nom.skjermede-personer-status-v1
    - name: LEESAH_TOPIC
      value: pdl.leesah-v1
    - name: AMT_NAV_BRUKER_TOPIC
      value: amt.nav-bruker-personalia-v1
    - name: AMT_ARRANGOR_ANSATT_PERSONALIA_TOPIC
      value: amt.arrangor-ansatt-personalia-v1
    - name: AMT_NAV_ANSATT_PERSONALIA_TOPIC
      value: amt.nav-ansatt-personalia-v1
    - name: AMT_NAV_ENHET_TOPIC
      value: amt.nav-enhet-v1
    - name: OPPFOLGINGSPERIODE_TOPIC
      value: pto.oppfolgingsperiode-v1
    - name: VEILARBVEDTAKSSTOTTE_SCOPE
      value: api://dev-gcp.obo.veilarbvedtaksstotte/.default
    - name: VEILARBVEDTAKSSTOTTE_URL
      value: http://veilarbvedtaksstotte.obo
    - name: INNSATSGRUPPE_TOPIC
      value: pto.siste-14a-vedtak-v1

  gcp:
    sqlInstances:
      - name: amt-person-service
        tier: db-f1-micro
        collation: nb_NO.UTF8
        type: POSTGRES_14
        databases:
          - name: amt-person-service
            envVarPrefix: DB

  observability:
      autoInstrumentation:
        enabled: true
        runtime: java
      logging:
        destinations:
          - id: elastic
          - id: loki
