kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-person-service
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-person-service.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 10
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: digdir-krr-proxy.intern.dev.nav.no
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: norg2.dev-fss-pub.nais.io
        - host: nom-api.intern.dev.nav.no
        - host: veilarbarena.dev-fss-pub.nais.io
  env:
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.digdir-krr-proxy/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.intern.dev.nav.no
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-fss.pto.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io
    - name: NORG_URL
      value: https://norg2.dev-fss-pub.nais.io
    - name: POAO_TILGANG_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: NOM_SCOPE
      value: api://dev-gcp.nom.nom-api/.default
    - name: NOM_URL
      value: https://nom-api.intern.dev.nav.no
    - name: VEILARBARENA_SCOPE
      value: api://dev-fss.pto.veilarbarena/.default
    - name: VEILARBARENA_URL
      value: https://veilarbarena.dev-fss-pub.nais.io
    - name: ENDRING_PAA_BRUKER_TOPIC
      value: pto.endring-paa-oppfolgingsbruker-v2
    - name: SISTE_TILORDNET_VEILEDER_TOPIC
      value: pto.siste-tilordnet-veileder-v1
    - name: AKTOR_V2_TOPIC
      value: pdl.aktor-v2
    - name: SKJERMEDE_PERSONER_STATUS_TOPIC
      value: nom.skjermede-personer-status-v1
    - name: LEESAH_TOPIC
      value: pdl.leesah-v1

  gcp:
    sqlInstances:
      - name: amt-person-service
        collation: nb_NO.UTF8
        type: POSTGRES_14
        databases:
          - name: amt-person-service
            envVarPrefix: DB
