kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-person-service
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://amt-person-service.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  startup:
    path: /internal/health/liveness
    initialDelay: 10
    failureThreshold: 30
    periodSeconds: 5
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: poao-tilgang
          namespace: poao
          cluster: prod-gcp
      external:
        - host: pdl-api.prod-fss-pub.nais.io
        - host: digdir-krr-proxy.intern.nav.no
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: norg2.prod-fss-pub.nais.io
        - host: nom-api.intern.nav.no
  env:
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io
    - name: DIGDIR_KRR_PROXY_SCOPE
      value: api://prod-gcp.team-rocket.digdir-krr-proxy/.default
    - name: DIGDIR_KRR_PROXY_URL
      value: https://digdir-krr-proxy.intern.nav.no
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://prod-fss.pto.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.prod-fss-pub.nais.io
    - name: NORG_URL
      value: https://norg2.prod-fss-pub.nais.io
    - name: POAO_TILGANG_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: POAO_TILGANG_SCOPE
      value: api://prod-gcp.poao.poao-tilgang/.default
    - name: NOM_SCOPE
      value: api://prod-gcp.nom.nom-api/.default
    - name: NOM_URL
      value: https://nom-api.intern.nav.no
