package no.nav.amt.person.service.navbruker

enum class InnsatsgruppeV1 {
	STANDARD_INNSATS,
	SITUASJONSBESTEMT_INNSATS,
	SPESIELT_TILPASSET_INNSATS,
	GRADERT_VARIG_TILPASSET_INNSATS,
	VARIG_TILPASSET_INNSATS,
}

enum class InnsatsgruppeV2 {
	GODE_MULIGHETER,
	TRENGER_VEILEDNING,
	TRENGER_VEILEDNING_NEDSATT_ARBEIDSEVNE,
	JOBBE_DELVIS,
	LITEN_MULIGHET_TIL_A_JOBBE,
	;

	companion object {
		fun InnsatsgruppeV2.toV1(): InnsatsgruppeV1 =
			when (this) {
				GODE_MULIGHETER -> InnsatsgruppeV1.STANDARD_INNSATS
				TRENGER_VEILEDNING -> InnsatsgruppeV1.SITUASJONSBESTEMT_INNSATS
				TRENGER_VEILEDNING_NEDSATT_ARBEIDSEVNE -> InnsatsgruppeV1.SPESIELT_TILPASSET_INNSATS
				JOBBE_DELVIS -> InnsatsgruppeV1.GRADERT_VARIG_TILPASSET_INNSATS
				LITEN_MULIGHET_TIL_A_JOBBE -> InnsatsgruppeV1.VARIG_TILPASSET_INNSATS
			}
	}
}

enum class HovedmalMedOkeDeltakelse {
	SKAFFE_ARBEID,
	BEHOLDE_ARBEID,
	OKE_DELTAKELSE,
}
