server.port=8086
management.server.port=8086
logging.config=classpath:logback-local.xml

AZURE_OPENID_CONFIG_ISSUER=http://localhost:9000/azure
AZURE_APP_CLIENT_ID=amt-person-service
AZURE_APP_CLIENT_SECRET=local-secret
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT=http://localhost:9000/azure/token

DB_JDBC_URL=jdbc:postgresql://localhost:5432/amt_person_service_db
spring.datasource.username=myuser
spring.datasource.password=mypassword

PDL_URL=http://localhost:9002/pdl
PDL_SCOPE=api://pdl/.default
DIGDIR_KRR_PROXY_URL=http://localhost:9002/digdir-krr-proxy
DIGDIR_KRR_PROXY_SCOPE=api://digdir-krr-proxy/.default
VEILARBOPPFOLGING_URL=http://localhost:9002
VEILARBOPPFOLGING_SCOPE=api://veilarboppfolging/.default
VEILARBVEDTAKSSTOTTE_URL=http://localhost:9002
VEILARBVEDTAKSSTOTTE_SCOPE=api://veilarbvedtaksstotte/.default
NORG_URL=http://localhost:9002/norg
KODEVERK_URL=http://localhost:9002/felles-kodeverk
KODEVERK_SCOPE=api://kodeverk/.default
POAO_TILGANG_URL=http://localhost:9002/poao-tilgang
POAO_TILGANG_SCOPE=api://poao-tilgang/.default
NOM_URL=http://localhost:9002/nom
NOM_SCOPE=api://nom/.default
AO_OPPFOLGINGSKONTOR_URL=http://localhost:9002/ao-oppfolgingskontor
AO_OPPFOLGINGSKONTOR_SCOPE=api://ao-oppfolgingskontor/.default

kafka.schema.registry.url=http://localhost:8081
kafka.schema.registry.username=local
kafka.schema.registry.password=local

app.env.sisteOppfolgingsperiodeTopic=siste-oppfolgingsperiode-topic
app.env.sisteTilordnetVeilederTopic=siste-tilordnet-veileder-topic
app.env.aktorV2Topic=aktor-v2-topic
app.env.skjermedePersonerTopic=skjermede-personer-topic
app.env.leesahTopic=leesah-topic
app.env.deltakerV2Topic=deltaker-v2-topic
app.env.oppfolgingsperiodeTopic=oppfolgingsperiode-topic
app.env.innsatsgruppeTopic=innsatsgruppe-topic
app.env.amtNavBrukerTopic=amt-nav-bruker-topic
app.env.amtNavEnhetTopic=amt-nav-enhet-topic
app.env.amtArrangorAnsattPersonaliaTopic=amt-arrangor-ansatt-personalia-topic
app.env.amtNavAnsattPersonaliaTopic=amt-nav-ansatt-personalia-topic

app.poststed.run-on-startup=true
